------------INITIALISATION DE LA BASE DE DONNEE---------------------
DROP DATABASE IF EXISTS QUIZZ; --SUPPRESSION SI EXISTENCE
CREATE DATABASE IF NOT EXISTS QUIZZ;--CREATION SI NON EXISTENCE

USE QUIZZ;--UTILISATION DE LA BASE DE DONNEE


------------CREATION DES TABLES DE LA BASE DE DONNEE----------------

CREATE TABLE IF NOT EXISTS USERS ( --CREATION DE LA TABLE UTILISATEUR SI NON EXISTENCE
    ID_USERS INT PRIMARY KEY AUTO_INCREMENT,
    NAME_USERS VARCHAR(50) NOT NULL,
    PASS_USERS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SCORE ( --CREATION DE LA TABLE SCORE SI NON EXISTENCE
    ID_SCORE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USERS INT, 
    FOREIGN KEY (ID_USERS) REFERENCES USERS (ID_USERS);
    LEVEL_SCORE VARCHAR(50)
);